### ISSUE TITLE
Add to puppetlabs-stdlib

### ISSUE THREAD

**Issue by baurmatt** [thrnio/puppet-ip#3]
I would like to see this implemented in [puppetlabs-stdlib](https://github.com/puppetlabs/puppetlabs-stdlib). Did you try to get it in?

**Comment by thrnio** [comment]
No, for two reasons:

1. When I first wrote it, [puppetlabs-stdlib](https://github.com/puppetlabs/stdlib) didn't have any type aliases yet.
2. I liked being able to write `IP::Address`, etc., instead of `Stdlib::Ip::Address` or whatever.

That said, stdlib does have `Stdlib::Compat::Ip_address`, `Stdlib::Compat::Ipv4`, and `Stdlib::Compat::Ipv6`.
